# This currently does nothing. We have moved to GitHub action, but this is kept
# until wlibo666 has disabled this project in AppVeyor.
version: '{build}'
clone_folder: C:\gopath\src\github.com\wlibo666\afero
environment:
  GOPATH: C:\gopath
build_script:
- cmd: >-
    go version

